application/bookfocusing/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, SubmitField
from wtforms.validators import DataRequired


class UserForm(FlaskForm):
    name = StringField('name', validators=[DataRequired()])
    student_id = StringField('studentID', validators=[DataRequired()])
    passWord = TextAreaField('PassWord', validators=[DataRequired()])
    Manager = SelectField('Manager', choices=[("False", "False"), ("True", "True")], validators=[DataRequired()])
    submit = SubmitField("Add todo")

application/bookfocusing/routes.py
from werkzeug.datastructures import RequestCacheControl
from application import app
from flask import Blueprint, render_template, request, redirect, flash, url_for, session, abort
from .forms import UserForm
from application import db
from datetime import datetime
from functools import wraps


from bson import ObjectId
import bcrypt



# 관리자 권한
def manager_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'manager_auth' in session:
            return f(*args, **kwargs)
        else:
            flash("관리자 권한이 필요합니다.") 
            return redirect(url_for('bookfocusing.main')) 
    return wrap


# 로그인 후 요청가능
def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return f(*args, **kwargs)
        else:
            flash("로그인이 필요합니다.")
            return redirect(url_for('bookfocusing.main'))
    return wrap


        
# 블루프린트로 페이지 관리
bookfocusing = Blueprint(
    "bookfocusing",
    __name__,
    template_folder="templates",
    static_folder="static"
)


# 메인 페이지
@bookfocusing.route("/main")
def main():
    return render_template("bookfocusing/main.html")


# 회원관리 페이지 (관리자만 가능)
@bookfocusing.route("/users")
@login_required
@manager_required
def users():
    page = request.args.get("page", 1, type=int)
    per_page = 3
    name_query = request.args.get("name", "")

    total_users = db.user_info.count_documents({"name": {"$regex": name_query, "$options": "i"}})
    total_pages = (total_users + per_page - 1) // per_page

    todos = []
    cursor = db.user_info.find({"name": {"$regex": name_query, "$options": "i"}}).sort("date_created", -1).skip((page - 1) * per_page).limit(per_page)
    for todo in cursor:
        todo["_id"] = str(todo["_id"])
        todo["date_created"] = todo["date_created"].strftime("%b %d %Y %H:%M%S")
        todos.append(todo)

    return render_template("bookfocusing/users.html", todos=todos, current_page=page, total_pages=total_pages)


# 회원가입
@bookfocusing.route("/signup", methods=["POST", "GET"])
def signup():
    if request.method == "POST":
        form = UserForm(request.form)
        user = {
            "user_name": form.name.data,
            "student_ID": form.student_id.data,
            "password": form.passWord.data,
            "Manager": form.Manager.data
        }

        check_user = db.user_info.find_one({"studentID": user['student_ID']})

        if check_user is None:
            hashpass = bcrypt.hashpw(user['password'].encode('UTF-8'), bcrypt.gensalt())
            db.user_info.insert_one({
                "name": user['user_name'],
                "studentID": user['student_ID'],
                "PassWord": hashpass,
                "Manager": user['Manager'],
                "date_created": datetime.utcnow()
            })

            flash("successfully signed up", "success")
            return redirect(url_for("bookfocusing.main"))
        flash("You already signed up")
        return redirect(url_for("bookfocusing.signup"))
    else:
        form = UserForm()
    return render_template("bookfocusing/signup.html", form=form)


# 업데이트
@login_required
@manager_required
@bookfocusing.route("/update_todo/<id>", methods=['POST', 'GET'])
def update_todo(id):
    if request.method == "POST":
        form = UserForm(request.form)
        user_name = form.name.data
        student_ID = form.student_id.data
        password = form.passWord.data
        Manager: form.Manager.data

        db.user_info.find_one_and_update({"_id": ObjectId(id)}, {"$set": {
            "name": user_name,
            "studentID": student_ID,
            "PassWord": password,
            "Manager": Manager,
            "date_created": datetime.utcnow()
        }})
        flash("Todo successfully updated", "success")
        return redirect(url_for("bookfocusing.users"))
    else:
        form = UserForm()

        todo = db.user_info.find_one_or_404({"_id": ObjectId(id)})
        form.name.data = todo.get("name", None)
        form.student_id.data = todo.get("studentID", None)
        form.passWord.data = todo.get("PassWord", None)
        form.Manager.data = todo.get("Manager", None)
    return render_template("bookfocusing/signup.html", form=form)

# 삭제
@bookfocusing.route("/delete_todo/<id>")
@login_required
@manager_required
def delete_todo(id):
    db.user_info.find_one_and_delete({"_id": ObjectId(id)})
    flash("Todo successfully deleted", "success")
    return redirect(url_for("bookfocusing.users"))


# 로그인 페이지
@bookfocusing.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        form = UserForm(request.form)
        userin = {
            "student_ID": form.student_id.data,
            "password": form.passWord.data
        }

        user_login = db.user_info.find_one({"studentID": userin['student_ID']})

        if user_login:
            if bcrypt.hashpw(userin['password'].encode('UTF-8'), user_login['PassWord']) == user_login['PassWord']:
                del userin['password']
                session['logged_in'] = True
                session['userin'] = userin
                if user_login['Manager'] == "True":
                    session['manager_auth'] = True
                return redirect(url_for('bookfocusing.main'))
        flash("유효하지 않은 로그인입니다.")
        return redirect(url_for("bookfocusing.login"))
    else:
        form = UserForm()
    return render_template("bookfocusing/login.html", form=form)


# 로그아웃
@bookfocusing.route("/logout")
def logout():
    session.clear()
    return redirect(url_for('bookfocusing.main'))

application/bookfocusing/templates/bookfocusing/layout.html
<!DOCTYPE html>
<html lang="en">
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" 
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
    crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js">

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.12.5/dist/sweetalert2.all.min.js"></script>
    
    <link href="static/{% block link %}{% endblock %}" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('bookfocusing.static', filename='style.css')}}" />

    {% if title %}
        <title>Flask - {{ title }}</title>
    {% else %}
        <title>ㅇㅇ대학교 도서관에 오신 걸 환영합니다</title>
    {% endif %}
  </head>
  <body>
    <header>
      
      <nav class="navbar navbar-expand-lg navbar-light bg-danger">
          <a class="navbar-brand text-white" href="{{url_for('bookfocusing.main') }}" style="margin-left: 10px;">BookFocusing</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link text-white" href="{{url_for('search.books') }}">도서검색</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  관리자
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{{url_for('bookfocusing.users') }}">회원관리</a></li>
                  <li><a class="dropdown-item" href="{{url_for('search.management') }}">도서관리</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{{url_for('search.add_book') }}">도서추가</a></li>
                </ul>
              </li>

              {% if session.logged_in %}
              <li class="nav-item">
                <a class="nav-link text-white" href="{{url_for('bookfocusing.logout') }}">로그아웃</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </nav>
  </header>

 
    
    <main class="container-fluid">
      <div class="row">
        <div class="col-md-2"></div>

        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <script>
                Swal.fire({
                  title: "{{ category.title() }}",
                  text: "{{ message }}",
                  icon: "{{ category }}",
                  closeOnConfirm: false
                })
              </script>
            {% endfor %}
          {% endif %}
        {% endwith %}

          {% block content %}
          {% endblock content %}
        </div>

        <div class="col-md-2"></div>
      </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

application/bookfocusing/templates/bookfocusing/login.html
{% extends "bookfocusing/layout.html" %}
{% block content %}
<div>
    <form action="" method="POST">
        {{ form.csrf_token() }}
        <fieldset class="form-group">
            <legend style="margin-top:70px ; height:80px ; font-size:30px">로그인</legend>

            <div class="form-group">
                {{ form.student_id.label(class="form-control-label") }}
                {% if form.student_id.errors %}
                    {{ form.student_id(class="form-control form-control is-invalid") }}
                    {% for error in form.student_id.errors %}
                        <div class="invalid-feedback">
                            <span>{{ error }}</span>
                        </div>
                    {% endfor %}
                {% else %}
                    {{ form.student_id(class="form-control form-control") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.passWord.label(class="form-control-label") }}
                {% if form.passWord.errors %}
                    {{ form.passWord(class="form-control form-control is-invalid") }}
                    {% for error in form.passWord.errors %}
                        <div class="invalid-feedback">
                            <span>{{ error }}</span>
                        </div>
                    {% endfor %}
                {% else %}
                    {{ form.passWord(class="form-control form-control") }}
                {% endif %}
            </div>


            <div class="form-group">
                <input class="btn btn-outline-info" id="submit" name="submit" type="submit" value="로그인">


        </fieldset>
    </form>
</div>
{% endblock %}

application/bookfocusing/templates/bookfocusing/main.html
{% extends "bookfocusing/layout.html" %}
{% block link %}main.css{% endblock %}


<body>
{% block content %}
<div>
<div class='box'>
    <div class='wave -one'></div>
    <div class='wave -two'></div>
    <div class='wave -three'></div>
    <div class='title'>Book-Focusing</div>

    {% if session.logged_in %}
    {% else %}
    <p><a class="btn btn-danger col text-center position-absolute top-50 start-50 translate-middle"  href="{{url_for('bookfocusing.signup') }}"  style="height: 80px; font-size: 40px; width: 500px; margin-top:700px; margin-left:-120px;" tabindex="-1" role="button" aria-disabled="true">회원가입</a></p>
    <p><a class="btn btn-light col text-center position-absolute top-100 start-50 translate-middle" href="{{url_for('bookfocusing.login') }}"  style="height: 80px; font-size: 40px; width: 500px; margin-top:800px; margin-left:-120px;" tabindex="-1" role="button" aria-disabled="true">로그인</a></p>
    {% endif %}


    <!--{{session['logged_in']}}
    {{session['user']}}-->
</div>
{% endblock %}
</body>

application/bookfocusing/templates/bookfocusing/signup.html
{% extends "bookfocusing/layout.html" %}
{% block content %}


<div>
    <form action="" method="POST">
        {{ form.csrf_token() }}
        <fieldset class="form-group">

            {% if session.logged_in %}
            <legend style="margin-top:70px ; height:80px ; font-size:30px">회원정보</legend>
            {% else %}
            <legend style="margin-top:70px ; height:80px ; font-size:30px">회원가입</legend>
            {% endif %}

            <div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                    {{ form.name(class="form-control form-control is-invalid") }}
                    {% for error in form.name.errors %}
                    <div class="invalid-feedback">
                        <span>{{ error }}</span>
                    </div>
                {% endfor %}
            {% else %}
                {{ form.name(class="form-control form-control") }}
            {% endif %}
            </div>

            <div class="form-group">
                {{ form.student_id.label(class="form-control-label") }}
                {% if form.student_id.errors %}
                    {{ form.student_id(class="form-control form-control is-invalid") }}
                    {% for error in form.student_id.errors %}
                        <div class="invalid-feedback">
                            <span>{{ error }}</span>
                        </div>
                    {% endfor %}
                {% else %}
                    {{ form.student_id(class="form-control form-control") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.passWord.label(class="form-control-label") }}
                {% if form.passWord.errors %}
                    {{ form.passWord(class="form-control form-control is-invalid") }}
                    {% for error in form.passWord.errors %}
                        <div class="invalid-feedback">
                            <span>{{ error }}</span>
                        </div>
                    {% endfor %}
                {% else %}
                    {{ form.passWord(class="form-control form-control") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.Manager.label(class="form-control-label") }}
                {% if form.Manager.errors %}
                    {{ form.Manager(class="form-control form-control is-invalid") }}
                    {% for error in form.Manager.errors %}
                        <div class="invalid-feedback">
                            <span>{{ error }}</span>
                        </div>
                    {% endfor %}
                {% else %}
                    {{ form.Manager(class="form-control form-control") }}
                {% endif %}
            </div>

            {% if session.logged_in %}
            <div class="form-group">
                <input class="btn btn-outline-info" id="submit" name="submit" type="submit" value="확인">
            {% else %}
            <div class="form-group">
                <input class="btn btn-outline-info" id="submit" name="submit" type="submit" value="등록">
            {% endif %}


        </fieldset>
    </form>
</div>


{% endblock %}

application/bookfocusing/templates/bookfocusing/users.html
{% extends "bookfocusing/layout.html" %}
{% block link %}users.css{% endblock %}
{% block content %}

<div class="mb-3" style="margin-top: 50px;">
    <form class="form-inline" action="{{ url_for('bookfocusing.users') }}" method="GET">
        <div class="form-group">
            <label for="searchName" class="mr-2">Search by Name:</label>
            <input type="text" class="form-control" id="searchName" name="name" placeholder="Enter name">
        </div>
        <button type="submit" class="btn btn-danger ml-2">Search</button>
    </form>
</div>

<div>
    {% for todo in todos %}
        <div class="card p-1 m-3">
            <div class="card-body">
                {% if todo.completed == "True" %}
                <h5 class="card-title"><del>{{ todo.name }}</del></h5>
                {% else %}
                <h5 class="card-title">{{ todo.name }}</h5>
                {% endif %}
                <p class="card-text text-muted">{{ todo.date_created }}</p>
                <p class="card-text">{{ todo.studentID }}</p>
                <p class="card-text">{{ todo.PassWord }}</p>
                
                <a href="{{ url_for('bookfocusing.update_todo', id=todo._id) }}" class="btn btn-outline-info btn-sm">정보수정</a>
                <a href="{{ url_for('bookfocusing.delete_todo', id=todo._id) }}" class="btn btn-outline-danger btn-sm">회원삭제</a>
            </div>
        </div>
    {% endfor %}
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination custom-pagination">
        {% if current_page > 1 %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('bookfocusing.users', page=current_page-1) }}">Previous</a>
            </li>
        {% endif %}
        {% for page_num in range(1, total_pages + 1) %}
            <li class="page-item {% if page_num == current_page %}active{% endif %}">
                <a class="page-link" href="{{ url_for('bookfocusing.users', page=page_num) }}">{{ page_num }}</a>
            </li>
        {% endfor %}
        {% if current_page < total_pages %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('bookfocusing.users', page=current_page+1) }}">Next</a>
            </li>
        {% endif %}
    </ul>
</nav>

<a href="{{ url_for('bookfocusing.signup') }}" class="btn btn-danger btn-floating btn-lg registration-btn">등록
</a>

{% endblock %}