application/search/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, SubmitField
from wtforms.validators import DataRequired


class BookForm(FlaskForm):
    title = StringField('title', validators=[DataRequired()])
    shelf = StringField('shelf', validators=[DataRequired()])
    block = TextAreaField('block', validators=[DataRequired()])
    writer = StringField('writer', validators=[DataRequired()])
    loan = SelectField('loan', choices=[("대출불가능", "대출불가능"), ("대출가능", "대출가능")], validators=[DataRequired()])
    flag = SelectField('loan', choices=[("1", "1"), ("0", "0")], validators=[DataRequired()])
    submit = SubmitField("Add todo")

application/search/routes.py
from flask.templating import render_template_string
from werkzeug.datastructures import RequestCacheControl

from application import app
from flask import Blueprint, render_template, request, redirect, flash, url_for
from .forms import BookForm
from application import db
from datetime import datetime
from functools import wraps

from bson import ObjectId
from bson.json_util import dumps

from application.bookfocusing.routes import login_required, manager_required

import time
from threading import Timer

login_required(wraps)
manager_required(wraps)


search = Blueprint(
    "search",
    __name__,
    template_folder="templates",
    static_folder="static"
)


# book db
@search.route("/management")
@login_required
@manager_required
def management():
    page = request.args.get("page", 1, type=int)
    name = request.args.get("name")
    per_page = 2  # Number of items per page

    # Construct the query based on the search name if provided
    query = {}
    if name:
        query["title"] = {"$regex": name, "$options": "i"}  # Search by title

    total_books = db.book_info.count_documents(query)  # Get the total number of books
    total_pages = (total_books + per_page - 1) // per_page  # Calculate the total number of pages

    cursor = db.book_info.find(query).sort("date_created", -1).skip((page - 1) * per_page).limit(per_page)
    todos = []
    for todo in cursor:
        todo["_id"] = str(todo["_id"])
        todo["date_created"] = todo["date_created"].strftime("%b %d %Y %H:%M%S")
        todos.append(todo)

    return render_template("search/manage.html", todos=todos, current_page=page, total_pages=total_pages, search_name=name)


# 책 추가입력 creat
@search.route("/add_book", methods=["POST", "GET"])
@login_required
@manager_required
def add_book():
    if request.method == "POST":                # 입력받기
        form = BookForm(request.form)
        book_title = form.title.data
        book_shelf = form.shelf.data
        book_block = form.block.data
        book_writer = form.writer.data
        book_loan = form.loan.data

        db.book_info.insert_one({               # MongoDB에 insert
            "title": book_title,
            "shelf": book_shelf,
            "block": book_block,
            "writer": book_writer,
            "loan": book_loan,
            "flag": '0',
            "date_created": datetime.utcnow()
        })
        flash("Todo successfully added", "success")         # 성공했다는 flask창
        return redirect(url_for("search.management"))
    else:
        form = BookForm()
    return render_template("search/crud_book.html", form=form)


# book db update
@search.route("/update_book/<id>", methods=['POST', 'GET'])
@login_required
@manager_required
def update_book(id):
    if request.method == "POST":
        form = BookForm(request.form)
        book_title = form.title.data
        book_shelf = form.shelf.data
        book_block = form.block.data
        book_writer = form.writer.data
        book_loan = form.loan.data

        db.book_info.find_one_and_update({"_id": ObjectId(id)}, {"$set": {
            "title": book_title,
            "shelf": book_shelf,
            "block": book_block,
            "writer": book_writer,
            "loan": book_loan,
            "flag": '0',
            "date_created": datetime.utcnow()
        }})
        flash("Todo successfully updated", "success")
        return redirect(url_for("search.management"))
    else:
        form = BookForm()

        search = db.book_info.find_one_or_404({"_id": ObjectId(id)})
        form.title.data = search.get("title", None)
        form.shelf.data = search.get("shelf", None)
        form.block.data = search.get("block", None)
        form.writer.data = search.get("writer", None)
        form.loan.data = search.get("loan", None)
    return render_template("search/crud_book.html", form=form)


# book db delete
@login_required
@manager_required
@search.route("/delete_book/<id>")
@login_required
def delete_book(id):
    db.book_info.find_one_and_delete({"_id": ObjectId(id)})
    return redirect(url_for("search.management"))

#도서 검색
@search.route("/books", methods=["POST", "GET"])
def books():
    if request.method == 'POST':
        form = BookForm(request.form)
        needbook = form.title.data
        # db.book_info.find_one({"title": txt})
        return redirect(url_for("search.book", needbook=needbook))
    else:
        form = BookForm()
    return render_template("search/books.html", form=form)


@search.route("/book/<needbook>")
def book(needbook):
    page = request.args.get("page", 1, type=int)
    per_page = 3  # Number of items per page

    # Calculate the skip value based on the current page
    skip = (page - 1) * per_page

    needs = []
    total_needs = db.book_info.count_documents({"title": needbook})
    total_pages = (total_needs + per_page - 1) // per_page

    for need in db.book_info.find({"title": needbook}).skip(skip).limit(per_page):
        need["_id"] = str(need["_id"])
        needs.append(need)

    return render_template("search/list.html", needs=needs, total_pages=total_pages)


@search.route("/flag/<id>")
def flag(id):
    db.book_info.find_one_and_update({"_id": ObjectId(id)}, {"$set": {"flag": '1'}})
    flash("블럭이 곧 작동됩니다. 해당하는 책장으로 이동해주십시오.")
    return redirect(url_for("search.books"))

application/search/templates/search/books.html
{% extends "bookfocusing/layout.html" %}
{% block link %}books.css{% endblock %}
{% block content %}
<div>
    <form action="" method="POST">
        {{ form.csrf_token() }}
        <fieldset class="form-group">
            <legend style="margin-top:70px ; height:80px ; font-size:30px">도서검색</legend>

            
                <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control is-invalid") }}
                    {% for error in form.title.errors %}
                    <div class="invalid-feedback">
                        <span>{{ error }}</span>
                    </div>
                {% endfor %}
            {% else %}
                {{ form.title(class="form-control form-control") }}
            {% endif %}
                </div>
            
            <div class="form-group">
                <input class="btn btn-outline-info" id="submit" name="submit" type="submit" value="검색">
                
        </fieldset>
    </form>
</div>
{% endblock %}

application/search/templates/search/crud_book.html
{% extends "bookfocusing/layout.html" %}
{% block content %}
<div>
    <form action="" method="POST">
        {{ form.csrf_token() }}
        <fieldset class="form-group">
            <legend style="margin-top:70px ; height:80px ; font-size:30px">도서추가</legend>

            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control is-invalid") }}
                    {% for error in form.title.errors %}
                    <div class="invalid-feedback">
                        <span>{{ error }}</span>
                    </div>
                {% endfor %}
            {% else %}
                {{ form.title(class="form-control form-control") }}
            {% endif %}
            </div>

            <div class="form-group">
                {{ form.shelf.label(class="form-control-label") }}
                {% if form.shelf.errors %}
                    {{ form.shelf(class="form-control form-control is-invalid") }}
                    {% for error in form.shelf.errors %}
                        <div class="invalid-feedback">
                            <span>{{ error }}</span>
                        </div>
                    {% endfor %}
                {% else %}
                    {{ form.shelf(class="form-control form-control") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.block.label(class="form-control-label") }}
                {% if form.block.errors %}
                    {{ form.block(class="form-control form-control is-invalid") }}
                    {% for error in form.block.errors %}
                        <div class="invalid-feedback">
                            <span>{{ error }}</span>
                        </div>
                    {% endfor %}
                {% else %}
                    {{ form.block(class="form-control form-control") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.writer.label(class="form-control-label") }}
                {% if form.writer.errors %}
                    {{ form.writer(class="form-control form-control is-invalid") }}
                    {% for error in form.writer.errors %}
                        <div class="invalid-feedback">
                            <span>{{ error }}</span>
                        </div>
                    {% endfor %}
                {% else %}
                    {{ form.writer(class="form-control form-control") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.loan.label(class="form-control-label") }}
                {% if form.loan.errors %}
                    {{ form.loan(class="form-control form-control is-invalid") }}
                    {% for error in form.loan.errors %}
                        <div class="invalid-feedback">
                            <span>{{ error }}</span>
                        </div>
                    {% endfor %}
                {% else %}
                    {{ form.loan(class="form-control form-control") }}
                {% endif %}
            </div>


            <div class="form-group">
                <input class="btn btn-outline-info" id="submit" name="submit" type="submit" value="도서추가">


        </fieldset>
    </form>
</div>
{% endblock %}

application/search/templates/search/layout.html
<!DOCTYPE html>
<html lang="en">
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" 
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
    crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js">

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.12.5/dist/sweetalert2.all.min.js"></script>
    
    <link href="static/{% block link %}{% endblock %}" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('search.static', filename='style.css')}}" />

    {% if title %}
        <title>Flask - {{ title }}</title>
    {% else %}
        <title>ㅇㅇ대학교 도서관에 오신 걸 환영합니다</title>
    {% endif %}
  </head>
  <body>
    {%if session %}
    <header>
      
      <nav class="navbar navbar-expand-lg navbar-light bg-danger">
          <a class="navbar-brand text-white" href="{{url_for('bookfocusing.main') }}">BookFocusing</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link text-white" href="{{url_for('search.books') }}">도서검색</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  관리자
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{{url_for('bookfocusing.users') }}">회원관리</a></li>
                  <li><a class="dropdown-item" href="{{url_for('search.management') }}">도서관리</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{{url_for('search.add_book') }}">도서추가</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{{url_for('bookfocusing.logout') }}">로그아웃</a>
              </li> 
            </ul>
          </div>
        </nav>
  </header>

  {% else %}
  <header>
      
    <nav class="navbar navbar-expand-lg navbar-light bg-danger">
        <a class="navbar-brand text-white" href="{{url_for('bookfocusing.main') }}">BookFocusing</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link text-white" href="{{url_for('search.books') }}">도서검색</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                관리자
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{url_for('bookfocusing.users') }}">회원관리</a></li>
                <li><a class="dropdown-item" href="{{url_for('search.management') }}">도서관리</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{{url_for('search.add_book') }}">도서추가</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>
</header>
{% endif%}

    
    <main class="container-fluid">
      <div class="row">
        <div class="col-md-2"></div>

        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <script>
                Swal.fire({
                  title: "{{ category.title() }}",
                  text: "{{ message }}",
                  icon: "{{ category }}",
                  closeOnConfirm: false
                })
              </script>
            {% endfor %}
          {% endif %}
        {% endwith %}

          {% block content %}
          {% endblock content %}
        </div>

        <div class="col-md-2"></div>
      </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

application/search/templates/search/list.html
{% extends "bookfocusing/layout.html" %}
{% block content %}
<div>
    {% for need in needs %}
        <div class="card p-1 m-3">
            <div class="card-body">

            <p class="card-text">{{ need.title }}</p>
            <p class="card-text">{{ need.shelf}}</p>
            <p class="card-text">{{ need.block}}</p>
            <p class="card-text">{{ need.writer}}</p>
            <p class="card-text">{{ need.loan}}</p>

            <a href="{{url_for('search.flag', id=need._id) }}" class="btn btn-outline-info btn-sm">찾기</a>    

        </div>
    </div>
    {% endfor %}
</div>

<div class="pagination">
  {% if total_pages > 1 %}
      <ul class="pagination">
          {% for page_num in range(1, total_pages + 1) %}
              <li class="page-item {% if page_num == page %}active{% endif %}">
                  <a class="page-link" href="{{ url_for('search.book', needbook=needbook, page=page_num) }}">{{ page_num }}</a>
              </li>
          {% endfor %}
      </ul>
  {% endif %}
</div>

{% endblock %}

application/search/templates/search/manage.html
{% extends "bookfocusing/layout.html" %}
{% block link %}manage.css{% endblock %}
{% block content %}

<div class="mb-3" style="margin-top: 50px;">
    <form class="form-inline" action="{{ url_for('search.management') }}" method="GET">
        <div class="form-group">
            <label for="searchName" class="mr-2">Search by Title:</label>
            <input type="text" class="form-control" id="searchName" name="name" placeholder="Enter title">
        </div>
        <button type="submit" class="btn btn-danger ml-2">Search</button>
    </form>
</div>

<div>
    {% for todo in todos %}
        <div class="card p-1 m-3">
            <div class="card-body">
                {% if todo.loan == "True" %}
                <h5 class="card-title"><del>{{ todo.name }}</del></h5>
                {% else %}
                <h5 class="card-title">{{ todo.name }}</h5>
                {% endif %}
                <p class="card-text text-muted">{{ todo.date_created }}</p>
                <p class="card-text">{{ todo.title }}</p>
                <p class="card-text">{{ todo.shelf}}</p>
                <p class="card-text">{{ todo.block}}</p>
                <p class="card-text">{{ todo.writer}}</p>
                <p class="card-text">{{ todo.loan}}</p>
                
                <a href="{{ url_for('search.update_book', id = todo._id) }}" class="btn btn-outline-info btn-sm">정보수정</a>
                <a href="{{ url_for('search.delete_book', id = todo._id) }}" class="btn btn-outline-danger btn-sm">회원삭제</a>
            </div>
        </div>
    {% endfor %}
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination custom-pagination">
        {% if current_page > 1 %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('search.management', name=request.args.get('name'), page=current_page-1) }}">Previous</a>
            </li>
        {% endif %}
        {% for page_num in range(1, total_pages + 1) %}
            <li class="page-item {% if page_num == current_page %}active{% endif %}">
                <a class="page-link" href="{{ url_for('search.management', name=request.args.get('name'), page=page_num) }}">{{ page_num }}</a>
            </li>
        {% endfor %}
        {% if current_page < total_pages %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('search.management', name=request.args.get('name'), page=current_page+1) }}">Next</a>
            </li>
        {% endif %}
    </ul>
</nav>

<a href="{{ url_for('search.add_book') }}" class="btn btn-danger btn-floating btn-lg registration-btn">도서추가
</a>
{% endblock %}